### DISCUSSION TITLE
Not able to disable opengrok mirror feature

### DISCUSSION THREAD

**Discussion by kee98** [oracle/opengrok#4272] [Q&A]
This could be similar to my previous question that I asked for suggester: https://github.com/oracle/opengrok/discussions/4266#discussioncomment-5516410

I am trying to debug the performance of my container and after disabling suggestor, I see now opengrok-mirror is occuping the process. However it doesn't take much resource but I think keeps container busy and reindexing doesn't start periodically.

To disable mirror, I tried adding 

```
            - name: NOMIRROR
              value: "true"
```

as environment variable of container... also created config file to disable mirror of all repos:

```
projects:
  .* :
    disabled: true
```

but still I see following commands in log:

```
command 'opengrok-mirror <command> failed with code -9, breaking
```

Am I again missing something? Kindly help.

**Comment by vladak** [comment]
This is recently introduced bug, will be fixed by PR #4274.

**Reply by jkjha** [reply]
you merged your changes right? I am still seeing mirror related logs even after appling above patch https://github.com/oracle/opengrok/pull/4274 ....

**Reply by vladak** [reply]
Yep, the changes should be in `master`.

**Reply by vladak** [reply]
What kind of logs do you see exactly ?

**Reply by vladak** [reply]
For the record, here's my `docker-compose` configuration:
```yml
version: "3"

# More info at https://github.com/oracle/opengrok/docker/
services:
  opengrok:
    container_name: opengrok-moje
    image: opengrok-dev:latest
    # image: opengrok/docker:latest
    # image: opengrok/docker:master
    ports:
      - "7777:8080/tcp"
      - "5000:5000/tcp"
    environment:
      #OPENGROK_LOG_LEVEL: 'debug'
      #SYNC_PERIOD_MINUTES: '0'
      NOMIRROR: 1
      # INDEXER_OPT: "-i d:vendor"
      API_TIMEOUT: 30
    # Volumes store your data between container upgrades
    volumes:
      - '~/opengrok/etc/:/opengrok/etc/'  # folder contains configuration.xml
      - '~/opengrok/src/:/opengrok/src/'  # source code
      - '~/opengrok/data/:/opengrok/data/'  # index and other things for source code

```

**Reply by jkjha** [reply]
My part of deployment.file:

```
      containers:
        - env:
            - name: SYNC_PERIOD_MINUTES
              value: "60"
            - name: WORKERS
              value: "50"
            - name: NOMIRROR
              value: "1"
            - name: API_TIMEOUT
              value: "60"
            - name: CHECK_INDEX
              value: "true"
            - name: OPENGROK_SCAN_REPOS
              value: "on"
            - name: OPENGROK_SCAN_DEPTH
              value: "8"
            - name: OPENGROK_GENERATE_HISTORY
              value: "on"
            - name: OPENGROK_SUGGESTTER_ENABLED
              value: "false"
            - name: P4CONFIG
              value: ".p4config"
            - name: READONLY_CONFIG_FILE
              value: "/opengrok/etc/read-only.xml"
```

and the container is filled with logs related to mirror (failed with error code 9) and reindexing failed with error code 1 (please check the image). I do not see any more detail about the failure to debug...but atleast mirror command should not run right, since its disabled.

<img width="1169" alt="Screenshot 2023-04-06 at 11 31 50 PM" src="https://user-images.githubusercontent.com/4188259/230460390-e3bf2f18-462b-4787-a729-524745636361.png">
