### DISCUSSION TITLE
Cost a lot cpu after 24h

### DISCUSSION THREAD

**Discussion by Ylarod** [oracle/opengrok#4432] [Q&A] [answered]
Hello, I use docker to host opengrok, the docker-compose file is like below.

```yaml
version: "3"

services:
  aosp_openresty:
    container_name: aosp_openresty
    image: openresty/openresty:alpine
    profiles:
       - service
    ports:
      - 8080:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/local/openresty/nginx/html
    restart: unless-stopped
    networks: 
      vpn:
        ipv4_address: 172.168.22.99

  aosp_tomcat_sdk21:
    container_name: aosp_tomcat_sdk21
    image: tomcat:10.1-jdk11
    profiles:
       - service
    volumes:
      - '/data/aospxref/webapps/android-5.0.0_r1:/usr/local/tomcat/webapps'
      - '/data/aospxref/src/android-5.0.0_r1:/opengrok/src/'
      - '/data/aospxref/etc/android-5.0.0_r1:/opengrok/etc/'
      - '/data/aospxref/data/android-5.0.0_r1:/opengrok/data/'
    restart: unless-stopped
    networks: 
      vpn:
        ipv4_address: 172.168.22.121

  aosp_opengrok_sdk21:
    container_name: aosp_opengrok_sdk21
    image: opengrok/docker:latest
    environment:
      SYNC_PERIOD_MINUTES: '0'
      URL_ROOT: '/android-5.0.0_r1'
    profiles:
       - init
    volumes:
       - '/data/aospxref/webapps/android-5.0.0_r1:/usr/local/tomcat/webapps'
       - '/data/aospxref/src/android-5.0.0_r1:/opengrok/src/'
       - '/data/aospxref/etc/android-5.0.0_r1:/opengrok/etc/'
       - '/data/aospxref/data/android-5.0.0_r1:/opengrok/data/'
    restart: unless-stopped
    networks: 
      vpn:
        ipv4_address: 172.168.22.221
```

I use opengrok to generate index and use a standalone tomcat image to provide service cause it's more stable.
But every day, I need to restart the container because it costs a lot of cpu and memory(before I limited it to 2GB)

I don't know why this occured, any help?

Thanks in advance.

<img width="821" alt="image" src="https://github.com/oracle/opengrok/assets/30978685/59a3c866-c463-42d9-9d18-332e1c97bde3">

After restart the container and wait for 1 minute (compile):

<img width="765" alt="image" src="https://github.com/oracle/opengrok/assets/30978685/9ade20b3-22d1-4798-b860-431b8ebe6b00">

top

![image](https://github.com/oracle/opengrok/assets/30978685/1c41d45f-7fa5-4a3c-8b3f-3d18d8b02c9e)
