### DISCUSSION TITLE
Not displaying history at folder layer for some projects

### DISCUSSION THREAD

**Discussion by simranjeetc** [oracle/opengrok#4438] [Q&A]
**Describe the bug**
Clicking on the folder history link throws an error for some repositories

Please refer to the folder structure in the below screenshot

- With the above folder structure, if the history link is clicked on any folder, it gives the above error
- This doesn't happen if the highlighted repository is kept at the parent folder
- This doesn't happen for other repositories i.e. clicking on history folder link for other repositories work just fine. The problem seems to be coming up only with the highlighted repo when it is placed at this nested level.
- The history link works irrespective if it is clicked at the file level

### Folder structure
![folder-structure-screenshot](https://github.com/oracle/opengrok/assets/4994904/147352a5-e3cd-44b7-8d05-514cbc52d502)

### Error
![image](https://github.com/oracle/opengrok/assets/4994904/363d12bd-d180-48a9-9fae-f43d330e77a4)

**Expected behavior**

Clicking on folder history link of the highlighted repo should display the history even in the nested folder

**Additional context**
Below are the logs 
```logs
17-Oct-2023 08:57:01.929 FINER [http-nio-8080-exec-8] org.opengrok.indexer.authorization.AuthorizationStack.isAllowed Authorization for "Verity" in "default stack" [required]
17-Oct-2023 08:57:01.929 FINER [http-nio-8080-exec-8] org.opengrok.indexer.authorization.AuthorizationStack.isAllowed Authorization for "Verity" in "default stack" [required] => true
17-Oct-2023 08:57:01.938 FINEST [http-nio-8080-exec-8] org.opengrok.indexer.history.HistoryGuru.getHistoryFromRepository '/opengrok/src/Verity/collection-center' in null is not eligible for history
17-Oct-2023 08:57:01.939 FINE [http-nio-8080-exec-8] org.apache.catalina.core.StandardHostValve.custom Processing ErrorPage[errorCode=404, location=/enoent]
17-Oct-2023 08:57:01.940 FINER [http-nio-8080-exec-8] org.opengrok.indexer.authorization.AuthorizationStack.isAllowed Authorization for "1_verity" in "default stack"
```


Using the below mentioned docker-compose file to deploy the opengrok image
```yaml

version: "3"

# More info at https://github.com/oracle/opengrok/docker/
services:
  opengrok-fas:
    container_name: opengrok-fas
    image: opengrok/docker:1.7.11
    restart: always
    volumes:
      - 'opengrok_data_fasa101023:/opengrok/data'
      - '/code/opengrok/src/fas/:/opengrok/src/'  # source code
      - '/code/opengrok/src/ABCCode/:/opengrok/src/ABCCode/' 
      - './etc_fas/:/opengrok/etc/'  # folder contains configuration.xml
      - './conf/:/usr/local/tomcat/conf'
    ports:
      - "9090:8080/tcp"
      - "5001:5000/tcp"
    environment:
      SYNC_PERIOD_MINUTES: '360'
      OPENGROK_LOG_LEVEL: 'INFO'
      NOMIRROR: 'true'
      INDEXER_OPT: '-H -S -R /opengrok/etc/read_only.xml'
    # Volumes store your data between container upgrades
volumes:
  opengrok_data_fasa101023:
networks:
  opengrok-fas:
~                                                                                                                                                                                                           
~                                                                                                                                                                                                           
~                                   


```
