### ISSUE TITLE
public OpenGrok demo - autodeploy on push with successful build and test

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#1740]
As asked in #1736 , there should be a public demo server that indexes OpenGrok code, running the latest `master`.

**Comment by vladak** [comment]
Need to sort out these things:
- [ ] deploy mechanism (some sort of Github hook ?) 
- [ ] nfra (Docker ?)
- [ ] domain name + registration
- [ ] hosting: AWS/Google cloud/Oracle cloud ?

**Comment by vladak** [comment]
I think Heroku is clear winner as it provides:
  - webapp deployment via webapp-runner (https://devcenter.heroku.com/articles/java-webapp-runner)
  - domain name (.herokuapp.com)
  - can deploy via Travis (https://docs.travis-ci.com/user/deployment/heroku/)

and is quite cheap ($7/month for Hobby version - https://www.heroku.com/pricing).

**Comment by vladak** [comment]
According to https://atmos.org/github-services/auto-deployment/ it is not necessary to deploy via Travis. One can deploy from Github directly to Heroku. For that 2 Services are needed:
  - Autodeploy - automatically creates deployment Github objects (https://developer.github.com/v3/repos/deployments/#create-a-deployment), can be set so that deployments are created only for successful CI runs ('Deploy on status').
  - HerokuBeta - performs the actual app deployment upon seeing new deployment object being created

This seems to be cleaner than deploying via Travis (and does not extend the dependency - Travis can be replaced by different CI in the future) and provides tracking via the deployment objects.

**Comment by vladak** [comment]
There is demo.opengrok.org however it would be nice to have this more seamless, ideally with ping-back via webhook to see if the deploy was successful.

**Comment by vladak** [comment]
Given that there is Docker image it would be shame not to use it since it wraps most of the complexity in usable package. Initially my idea was to deploy using the existing Travis pipeline however that is not needed - I stumbled upon https://stackoverflow.com/a/38593838/11582827 that recommends to use https://github.com/containrrr/watchtower that polls Docker image status and restarts existing containers with the latest image.

So, this basically boils down to couple of things:
  - finding a provider that can run Docker (ideally for free)
  - mapping `demo.opengrok.org` to the IP of the VPS
  - adding functionality to the OpenGrok Docker image to detect incompatible index and reindex from scratch (based on environment variable that would not be set by default)
  - making the Docker container to index demo repositories (OpenGrok repo would suffice)
    - maybe even create new Docker image based on the existing OpenGrok image that would do it

**Comment by Gilwe** [comment]
Hi, is this idea on hold?

**Comment by vladak** [comment]
Well, the Docker container works fine, it's just a matter of finding a place to host it and provision for each release.

**Comment by vladak** [comment]
For the time being I settled on Ubuntu image in Oracle Free Tier OCI. It runs the Docker image that is automatically updated by `watchtower`.

The configuration looks like this:
- `~/docker-compose.yml`:
```yml
version: "3"

# More info at https://github.com/oracle/opengrok/docker/
services:
  opengrok:
    container_name: opengrok-demo
    image: opengrok/docker:latest
    ports:
      - "80:8080/tcp"
    environment:
      SYNC_TIME_MINUTES: '10'
      READONLY_CONFIG_FILE: '/opengrok/etc/read-only.xml'
    # Volumes store your data between container upgrades
    volumes:
       - '~/opengrok/src/:/opengrok/src/'  # source code
       - '~/opengrok/etc/:/opengrok/etc/'  # folder contains configuration.xml
       - '~/opengrok/data/:/opengrok/data/'  # index and other things for source code
  # Automatically update all images and restart the respective containers.
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup --include-stopped --revive-stopped
```
- `~/opengrok/etc/read-only.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<java version="1.8.0_121" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration" id="Configuration0">

  <!-- enable definitions for historical revisions of files in the Navigate window -->
  <void property="ctags">                                                       
    <string>/usr/local/bin/ctags</string>                                       
  </void>                                                                       
  <void property="webappCtags">                                                 
    <boolean>true</boolean>                                                     
  </void>

 </object>
</java>
```
- `/etc/systemd/system/docker-opengrok-demo.service`:
```
[Unit]
Description=Docker Compose OpenGrok demo
Requires=docker.service
After=docker.service

[Service]
User=ubuntu
Group=ubuntu
WorkingDirectory=/home/ubuntu
ExecStart=/usr/bin/docker-compose up -d
ExecStop=/usr/bin/docker-compose down
TimeoutStartSec=0
Restart=on-failure
StartLimitBurst=3
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

Need to get the DNS entry set to point to the IP address.
