### ISSUE TITLE
create Github releases from Travis on tag

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#1967]
Currently the releases are created using the `tools/dorelease.py` script. It is run from the Ant `release` target and uses Github API to create the release and then uploads (Solaris) packages to it. I'd like to make this simpler by creating the release directly from Travis (will happen automatically if a tag is pushed). This would mean getting rid of the packages.

**Comment by vladak** [comment]
The only thing to solve is how to differentiate between pre-release and full release.

**Comment by vladak** [comment]
This will do the job:

```
deploy:
  # Pre-release
  - provider: releases
    script:
    - echo "$TRAVIS_TAG"
    - echo "$TRAVIS_BRANCH"
    prerelease: true
    api_key:
      secure: XXX
    file: README.md
    skip_cleanup: true
    on:
      repo: vladak/reltest
      tags: true
      condition: "$TRAVIS_TAG =~ rc[0-9]+$"
  # Full release
  - provider: releases
    script:
    - echo "$TRAVIS_TAG"
    - echo "$TRAVIS_BRANCH"
    api_key:
      secure: XXX
    file: README.md
    skip_cleanup: true
    on:
      repo: vladak/reltest
      tags: true
      condition: "! $TRAVIS_TAG =~ rc[0-9]+$"
```

2 release targets are needed since it does not seem possible to dynamically supply boolean value to the `prerelease` option.

The last remaining part is to generate the distribution from Maven.
