### ISSUE TITLE
Allow wildcards in mirror-config.yml

### ISSUE THREAD

**Issue by tulinkry** [oracle/opengrok#2568]
Support wildcards in mirror-config.yml. I would like to write the config somewhat like this

```yaml
#
# Per project configuration.
#
projects:
  group-*:
    ignored_repos:
      - /group-*/testdata/*
```

or even better would be (if the repository root wouldn't be necessary):
```yaml
#
# Per project configuration.
#
projects:
  group-*:
    ignored_repos:
      - testdata/*
```

This is actually the opengrok structure and my system doesn't have all the repository commands, so I would like to ignore the test data for my runs.
