### ISSUE TITLE
allow to specify disabled message payload in mirror.py

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3102]
**Is your feature request related to a problem? Please describe.**
The `mirror.py` script can execute a script or do a RESTful call for disabled projects. In the latter case more flexibility in the payload would be handy so that the users can determine the cause easily from the UI.

**Describe the solution you'd like**
If a project is disabled the value of the `disabled` property can be either boolean or string so the RESTful call will either use default message or custom, respectively.

Example:
```yaml
projects:
  foo:
    # no longer active but used to support customers
    disabled: true
  bar:
    disabled: disabled, upstream not reachable (as of 02/2020)
```

**Alternatives**
Use the default payload as a prefix.
