### ISSUE TITLE
tools need to have support for API bearer token

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3429]
To complement #3398, Python tools need to be able to specify the token too.

**Comment by vladak** [comment]
This really prompts the change of the syntax for the HTTP based commands in the `opengrok-sync` or `opengrok-mirror` configuration. For example for `DELETE` the header can be specified like this:
```yml
- command:
  - 'http://localhost:8080/source/api/v1/messages?tag=%PROJECT%'
  - DELETE
  - 'resync + reindex in progress'
  - 'Content-type': 'text/plain'
```
and `POST` has this ordering:
```yml
- command:
  - http://localhost:8080/source/api/v1/messages
  - POST
  - messageLevel: warning
    duration: PT1H
    tags: ['%PROJECT%']
    text: resync + reindex in progress
```
Converting this to dictionary (and allow multiple custom headers) would make more sense.
