### ISSUE TITLE
Docker sync.yml does not match with default URL in opengrok-sync

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3433]
When running `opengrok-sync` with the `docker/sync.yml` without -U:
```
RESTful command {'command': ['%URL%api/v1/messages', 'POST', {'messageLevel': 'warning', 'duration': 'PT1H', 'tags': ['%PROJECT%'], 'text': 'resync + reindex in progress'}]} failed: 404 Client Error:  for url: http://localhost:8080/sourceapi/v1/messages
```
The `sync.yml` contains:
```yml
- command:
  - '%URL%api/v1/messages'
  - POST
  - messageLevel: warning
    duration: PT1H
    tags: ['%PROJECT%']
    text: resync + reindex in progress
```
That's because the `start.py` Docker script tries hard to have the `URL` ending with slash. The URL defaults in the Python tools should be united with the Docker script (change either the script or the tools).
