### ISSUE TITLE
convert command list to dictionary

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#3453]
A list is currently used to set various API call properties in command sequence (URI, HTTP verb, data, headers). This is inconvenient when one wants to specify per command proxies or timeout value. Dictionary would be more flexible.

**Comment by vladak** [comment]
From:
```yml
- command:
  - http://foo:8080/source/api/v1/messages
  - POST
  - messageLevel: warning
    duration: PT1H
    tags: ['%PROJECT%']
    text: resync + reindex in progress
```
to something like:
```yml
- command:
  uri: http://foo:8080/source/api/v1/messages
  verb: POST
  data:
    messageLevel: warning
    duration: PT1H
    tags: ['%PROJECT%']
    text: resync + reindex in progress
  headers:
    one: two
    foo: bar
  timeout: 42
```
