### ISSUE TITLE
Docker start.py receives spurious SIGTERM signal

### ISSUE THREAD

**Issue by simranjeetc** [oracle/opengrok#3650]
**Describe the bug**
I have a project `jdk8-b120` which is causing opengrok server to shutdown.

I want to disable the sync and reindex for this project. Please find `mirror.yml` below

```yml
# Empty config file for opengrok-mirror
ignore_errors: true

projects:
  jdk8.*:
    disabled: true
    incoming_check: false
```

Despite doing this I still see reindex getting triggered(screenshot below) for this project. What am I missing here?
Also, how I can find what is causing the shutdown? Can suggester be the reason for the same?

I have used 1.4 for quite sometime and never had any such issues. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4994904/123216020-ba69e200-d4e6-11eb-907b-304a83194a40.png)

**Comment by vladak** [comment]
What do you mean by 'shutdown' exactly ?

**Comment by simranjeetc** [comment]
> What do you mean by 'shutdown' exactly ?

In my docker-compose file(below) you can find that I had to use `restart: always` option because the container was coming down. Upon looking at the logs(attached), I found that tomcat was starting time and again as I find `Starting Tomcat` in logs everytime it does.

Let me know if you need any other info for the same. 

[opengrok-log.tar.gz](https://github.com/oracle/opengrok/files/6707698/opengrok-log.tar.gz)

```yml
services:
  opengrok-1-7-11:
    container_name: opengrok-1.7.11
    image: opengrok/docker:1.7.11
    restart: always
    volumes:
      - 'opengrok_data1_7_11:/opengrok/data'
      - './src/:/opengrok/src/'  # source code
      - './etc/:/opengrok/etc/'  # folder contains configuration.xml
      - '/etc/localtime:/etc/localtime:ro'
      - './logs/:/usr/local/tomcat/logs/'
    ports:
      - "9090:8080/tcp"
      - "5001:5000/tcp"
    environment:
      SYNC_PERIOD_MINUTES: '30'
      INDEXER_OPT: '-H -P -G -R /opengrok/etc/read_only.xml'
    # Volumes store your data between container upgrades
volumes:
  opengrok_data1_7_11:
networks:
  opengrok-1-7-11:
```
