### ISSUE TITLE
Opengrok for very large project Google Repo based

### ISSUE THREAD

**Issue by shilpakangya** [oracle/opengrok#3664]
Hi, I am facing problem to create the Opengrok workspace from a very large project with multiple sub-repositories, which uses google repo tool. For this, I am unable to generate the mirror.yml tool using the opengrok-mirror tool since I am not aware of -H HEADER option, so I have manually created the mirror.yml. Even I have created readonly configuration for customize config. Can someone suggest to the example mirror.yml and readonly.xml file(as input config for indexer)? I am attaching these file for review. I am unable to generate the index even for the first time and I dont see the dropdown project on webapp. Can you pease helpUsing these file along with this command "docker run -d \
    --name opengrok \
    -p 80:8080/tcp \
    -e SYNC_PERIOD_MINUTES="10" \
	-e NOMIRROR="1" \
	-e CHECK_INDEX="1" \
	-e INDEXER_OPT="-W /opengrok/etc/configuration.xml -m 256 -H -P -S -G --progress -v -O on -T 3 --depth 9 --assignTags --renamedHistory on -R /opengrok/etc/readonly.xml" \
    -v /home/uic33723/opengrok_basic/src/:/opengrok/src/ \
    -v /home/uic33723/opengrok_basic/etc/:/opengrok/etc/ \
    -v /home/uic33723/opengrok_basic/data/:/opengrok/data/ \
    ogk_basic

I have attached the logs and the configuration used.
![open](https://user-images.githubusercontent.com/87486999/125808122-f6f505ea-d243-4274-a208-25171027d191.png)
[cfg.zip](https://github.com/oracle/opengrok/files/6824034/cfg.zip)

**Comment by shilpakangya** [comment]
Can I request you to help review my configuration files? Request your helps and inputs on this. Thanks

**Comment by vladak** [comment]
The per project settings in the read-only configuration look sane however in order to use with the official Docker image it is necessary to use the `READONLY_CONFIG_FILE` environment variable (see https://github.com/oracle/opengrok/tree/master/docker#environment-variables). Using the -R directly will thwart the functionality of the main Docker script.

**Comment by vladak** [comment]
As for using `opengrok-mirror` to sync Android repository tree, I'd like to try it one day, esp. for #3622.

**Comment by vladak** [comment]
The `mirror_v2.yml` file has some weird artifact on the last line that causes YAML parsing to fail. Once removed, it loads fine, however still contains some weird indentation which I am not sure will be processed correctly.

The initial section:
```yaml
commands:                                                                       
  repo:                                                                         
    # override repository command                                               
    command: /usr/local/bin/repo                                                
    sync: ['repo', 'sync','-cf']                                                
    # override incoming check with custom command (/my/custom/git is not called for incoming check)
    # incoming: ['/bin/echo', 'Syncing the Repo!']                              
    incoming: ['repo', 'sync', '-n']                                            
    incoming_check: true
```
will not work as intended - the `commands` section is meant to merely replace paths to commands executed.
If you want to specify path to the `repo` command, it should look like this:
```yaml
commands:
  repo: /usr/local/bin/repo
```
