### ISSUE TITLE
Repository Commands "value of 'git' under 'commands' is not string"

### ISSUE THREAD

**Issue by davjr96** [oracle/opengrok#3705]
**Describe the bug**
I have a few projects where the development team updates certain branches using a `git push --force` command. When the stock opengrok sync attempts to `git pull` it fails and fails the mirroring/index process. 
Using the config outlined in https://github.com/oracle/opengrok/wiki/Repository-synchronization#repository-commands I attempted the following in /opengrok/etc/mirror.yml

```
ignore_errors: true
commands:
  git:
    incoming: ['git', 'fetch', '--all']
    sync: ['git', 'reset', '--hard', 'origin/master']
```
I get the following error

```
Output from 'opengrok-mirror -c /opengrok/etc/mirror.yml -I -U http://localhost:8080/ maserati':
value of 'git' under 'commands' is not string
Configuration check failed, exiting
```

```
opengrok-indexer --version
1.7.17
```

This may be a case of me misunderstanding the documentation. If so, Is there a way to alter the git command for all repositories?
