### ISSUE TITLE
Indexer not working in Docker image when NOMIRROR is defined

### ISSUE THREAD

**Issue by jekunen** [oracle/opengrok#3723]
The Docker `start.py` doesn't create an empty `mirror.yml` when started with NOMIRROR defined but the indexer appears to require this file to be present even if NOMIRROR is defined and will not index anything if the file is missing.

**Last working release:** 1.7.13\
**First broken release:** 1.7.14\
**Still broken in:** 1.7.19

docker-compose.yml:

```yml
version: "3.7"
services:

  opengrok:
    image: opengrok/docker:1.7.19
    container_name: opengrok
    ports:
      - 8080:8080
    volumes:
      - /opt/opengrok/src:/opengrok/src
    environment:
      - NOMIRROR=1
      - CHECK_INDEX=1
      - SYNC_PERIOD_MINUTES=0
      - REST_PORT=5001
```

**Error message:**

```text
opengrok    | Tomcat is ready
opengrok    | Merging commands with environment
opengrok    | Sync starting
opengrok    | command 'opengrok-mirror -c /opengrok/etc/mirror.yml -I -U http://localhost:8080/ inventory' for project inventory failed with code 1, breaking
opengrok    | processing of project 'inventory' failed
opengrok    |   failed commands:
opengrok    |     'opengrok-mirror -c /opengrok/etc/mirror.yml -I -U http://localhost:8080/ inventory': 1
opengrok    |       cannot open '/opengrok/etc/mirror.yml': No such file or directory
opengrok    |       Cannot read config file from /opengrok/etc/mirror.yml
opengrok    |
opengrok    |
opengrok    | Output from 'opengrok-mirror -c /opengrok/etc/mirror.yml -I -U http://localhost:8080/ inventory':
opengrok    | cannot open '/opengrok/etc/mirror.yml': No such file or directory
opengrok    | Cannot read config file from /opengrok/etc/mirror.yml
opengrok    |
opengrok    | Sync done
opengrok    | Saving configuration to /opengrok/etc/configuration.xml
opengrok    | Waiting for reindex to be triggered
```
