### ISSUE TITLE
Using Repo sync command in mirror yaml using  docker release after 1.7.13

### ISSUE THREAD

**Issue by shilpakangya** [oracle/opengrok#3820]
**Describe the bug**
Using Repo sync command in mirror yaml after docker release 1.7.13

mirror configuration in deployment
          MIRROR: |
```yml
            commands:
              repo: /usr/local/bin/repo
              sync: ['repo', 'sync','-cf']
              incoming: ['repo', 'sync', '-n']
              incoming_check: true
```
sync configuration for deployment,
          SYNC: |
```yml
            commands:
            - command:
              - '%URL%api/v1/messages'
              - POST
              - messageLevel: warning
                duration: PT2H
                tags: ['%PROJECT%']
                text: resync + reindex in progress
            - command: [bash, -c, 'cd /opengrok/src/%PROJECT%']
            - command: [opengrok-mirror, -c, '/opengrok/etc/mirror.yml', -I, -U, '%URL%', '%PROJECT%']
            - command: [opengrok-reindex-project, --printoutput,
                --jar, /opengrok/lib/opengrok.jar, -U, '%URL%', -P, '%PROJECT%', --,
                -r, dirbased, -G, -m, '256', --leadingWildCards, 'on',
                --renamedHistory, 'on',
                -c, /usr/local/bin/ctags, -U, '%URL%', -H, '%PROJECT%']
              limits: {RLIMIT_NOFILE: 1024}
            - command:
              - '%URL%api/v1/messages?tag=%PROJECT%'
              - DELETE
              - 'resync + reindex in progress'
              - 'Content-type': 'text/plain'
            cleanup:
            - command:
              - '%URL%api/v1/messages?tag=%PROJECT%'
              - DELETE
              - 'resync + reindex in progress'
              - 'Content-type': 'text/plain'
```
Intial step to sync used as,
```
            repo init -u ssh://xxx
            repo sync -c
```
Expectation is,
Repo sync should work, as
- first time mirror should generate the index in case there is no Initial step
- With incremental changes, it should regenerate index only for changed files or sub repositories

Error message:
Repository Commands "value of 'sync' under 'commands' is not string

Can I request on how to support the above scenario and to resolve this error?

Thanks

**Comment by vladak** [comment]
Does this happen with the latest version too ?

**Comment by shilpakangya** [comment]
Hi,
On the kubernetes deployment, I am facing different issue while accessing the latest docker image 1.7.23 and 1.7.24. I am facing the Init:CrashLoopBackOff during deploy helm chart.

I do not face this issue while using Opengrok docker 1.7.23.

I have observed the error as mentioned earlier while using Opengrok docker 1.7.15.

**Comment by vladak** [comment]
This is a duplicate of #3705, fixed in 1.7.18. For proper `repo` support 1.7.29 is needed.

**Comment by vladak** [comment]
Proper configuration for `opengrok-mirror` should look like this:
```yml
commands:
  repo: /foo/bar/bin/repo
```
or like this:
```yml
commands:
  repo:
    command: /foo/bar/bin/repo
    sync: ['repo', 'sync','-cf']
    incoming: ['repo', 'sync', '-n']
```
