### ISSUE TITLE
Excluding directories during indexing not working

### ISSUE THREAD

**Issue by kule1015** [oracle/opengrok#3905]
Hi,

i have question concerning excluding directories in the directory `opengrok/src`. In the documentation is suggested that the environment variable  **INDEXER_OPT** is suitable for such configuration. I am using following compose configuration:

```yml
  opengrok:
    container_name: opengrok
    image: opengrok/docker:1.7.30
    ports:
      - "8080:8080/tcp"
      - "5000:5000"
    environment:
      SYNC_PERIOD_MINUTES: '0'
      WORKERS: '2'
      NOMIRROR: '1'
      CHECK_INDEX: '1'
      REST_PORT: 5000
      INDEXER_OPT: "-i d:vendor"
    volumes:
       - source-volume:/opengrok/src/ 
       - opengrok-index-volume:/opengrok/etc/  
       - opengrok-index-volume:/opengrok/data/ 
```

But still the directory `vendor` will be indexed. Do i use the option `-i` wrong?
