### ISSUE TITLE
Create opengrok docker image for arm64

### ISSUE THREAD

**Issue by santhu3064** [oracle/opengrok#3948]
**Is your feature request related to a problem? Please describe.**

Currently all official docker images are of amd64. Can an official docker image for the arm64 arch be published?

**Describe the solution you'd like**

Create docker image to based on Linux  arm64 arch

**Describe alternatives you've considered**

**Additional context**

Looking to run opengrok docker container on arm64 arch machines

**Comment by vladak** [comment]
The [Github Actions virtual environments](Standard_DS2_v2 virtual machines in Microsoft Azure) currently support x64 machines only: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources and the https://github.com/actions/virtual-environments/issues/2552 tracking the addition of arm64 environments remains closed due to Azure limitation.

Although self-hosted arm{,64} runners seem to be [possible](https://github.com/wbond/pi-github-runner), this is not the level of complexity I'd like to get into at this point.

**Comment by santhu3064** [comment]
@vladak  Thank you for the update. Are you going to consider this in the near future?
Can this feature will be open?

**Comment by vladak** [comment]
Sure, this is valid request. I'd like to have arm64 OpenGrok Docker images myself. It's just I don't want to invest the resources into the automated arm/arm64 image builds right now.

**Comment by der-eismann** [comment]
It's actually pretty easy to build multiarch images on GitHub actions, it just might take a while:
https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/

**Comment by vladak** [comment]
> It's actually pretty easy to build multiarch images on GitHub actions, it just might take a while: https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/

Thanks for the link. Building in Qemu is certainly a possibility.

**Comment by vladak** [comment]
The official Github Linux ARM64 runners are currently in public preview. Will have to [figure out](https://stackoverflow.com/a/66337328) how to push x86 and arm64 Docker images separately under the same set of version tags.

**Comment by der-eismann** [comment]
Ooh nice, didn't know about that. 
So from my PoV the emulation via qemu/buildx is still the easiest way, building the JAR in the native architecture and then creating arch-specific images where you just add the JAR and what else is necessary.

Another solution we also use at work is building and pushing images for both architectures, say `opengrok/docker:1.13.27-arm64` & `opengrok/docker:1.13.27-amd64`. Afterwards in a separate job you pull them, create a manifest and push the manifest as well.

Metacode:
```yaml
jobs:
  build_amd64:
    runs-on: [ubuntu-24.04]
    steps:
    - name: Build & Push
      uses: docker/build-push-action@v6
      with:
        tags: opengrok/docker:${version}-amd64

  build_arm64:
    runs-on: [ubuntu-24.04-arm]
    steps:
    - name: Build & Push
      uses: docker/build-push-action@v6
      with:
        tags: opengrok/docker:${version}-arm64

  create_manifest:
    runs-on: [linux]
    needs: [build_amd64, build_arm64]
    steps:
    - name: Create & Push manifest
      shell: bash
      run: |
        docker manifest create opengrok/docker:${version} "opengrok/docker:${version}-amd64" "opengrok/docker:${version}-arm64"
        docker push opengrok/docker:${version}
```
