### ISSUE TITLE
opengrok container stop syncing and indexing

### ISSUE THREAD

**Issue by jamesosbourn** [oracle/opengrok#4037]
**Describe the bug**
Running the opengrok container ver 1.7.35 all seems to be working as expected.  repository updates and index updates work as expected. 
 Then all of a sudden for now apparent reason they stop.  The container log simply outputs 'Sleeping for 600 seconds' over and over again.  The mirror sync does not run and the index does not run.  The web UI age shows no update to the last index timestamp.  There are occasional notifications that suggesters are being rebuilt and succeed but nothing further.

After restarting the container the same state is observed, all appears to be ok, repos are updated and indexing complete and then nothing.  I have run with Debug enabled and the messages are no different.  The tomcat process is still running and there are no indication of out of memory problems or anything.

Tried with mirror disabled and appears to make no difference to the situation.

**To Reproduce**
Running on Ubuntu 22.04 with Docker 20.10.17
Docker Compose configuration

```
version: "3"

# More info at https://github.com/oracle/opengrok/docker/
services:
  grok_container:
    container_name: grok_container
    image: opengrok/docker:1.7.35
    ports:
      - "80:8080/tcp"
    environment:
      # NOMIRROR: "yes"
      OPENGROK_LOG_LEVEL: "DEBUG"
      # SYNC_PERIOD_MINUTES: '60'
    # Volumes store your data between container upgrades
    volumes:
       - '/root/.ssh:/root/.ssh'  # ssh key
       - '/opengrok/src:/opengrok/src/'
       - '/opengrok/etc:/opengrok/etc/'
       - '/opengrok/data:/opengrok/data/'
       - '/opengrok/setenv.sh:/usr/local/tomcat/bin/setenv.sh'
    restart: always
```

The setenv.sh contains
```
JAVA_OPTS="$JAVA_OPTS -server"
JAVA_OPTS="$JAVA_OPTS -Xmx10g"
```

**Expected behaviour**
mirror/sync and indexing would run every 10 minutes as per the default sync variable

**Additional context**
Running with container version 1.6.9 does not show any of the same symptoms.  Only running with a subset of repositories to verify functionality before adding the rest for final use.  Tried modifying the mirror.yaml configuration to update the commands to verify incoming changes and git pull which also made no difference to the outcome of the checks.  The logs will eventually just show waiting for 600 seconds.

Java heap memory increased in case this was an issue as had been observed in the past with a larger number of respositories and after following the guidelines for tuning for large code bases.

At this point we may have to revert to the 1.6.9 version which seems to be stable.  Have tried a number of 1.7.x versions.  This would mean missing out on the updates that have been released in the 1.7 releases.
