### ISSUE TITLE
Global hook

### ISSUE THREAD

**Issue by mishka81** [oracle/opengrok#4365]
How to declare a "global" hook in mirror.yml, invoked for each project ?

Something like this : 
```
hookdir: /tmp/hooks
hook_timeout: 1200
hooks:
  pre: userland-pre.ksh
  post: userland-post.ksh
# projects
```

Note : I don't want to declare explicitly ALL of my projects here
