### ISSUE TITLE
All the indexing data lost after restarting container

### ISSUE THREAD

**Issue by jkjha** [oracle/opengrok#4398]
**Describe the bug**

I am using opengrok v1.12.12 in container. My indexer data is under a VM which is mounted to the container. I have 2 replicas of the opengrok pod that is running in my k8s environment. 

The deployment was running fine, but one day we noticed that the newly added projects are sometimes not getting listed on the projects dropdown list. On further investigation we found that, when UI hits one of the replica it ruturns the old project list and so new projects are not visible, however, when it hits other replica, it returns the newly added projects as well.

To fix this immediately, we tried to restart the deployment (Rollback and recreate the pod), but after recreating the pod, we were surprised to see data all the indexer data is gone. This was completely unexpected and our almost 3TB of indexed data was deleted. 

Can you please check in priority what could have caused this and how to avoid it. And any thing we can do to avoid it? 
This has caused too much impact on our productivity.

**To Reproduce**
1. Opengrok container with 2 replicas.
2. restart and rollback the deployment
3. Indexer data is lost.

(I have not tried above steps again)

Env variables:

```
        - env:
            - name: SYNC_PERIOD_MINUTES
              value: "120"
            - name: INDEXER_OPT
              value: "-A .vmodl:JavaAnalyzer"
            - name: WORKERS
              value: "10"
            - name: CHECK_INDEX
              value: "false"
            - name: NOMIRROR
              value: "1"
            - name: API_TIMEOUT
              value: "300"
            - name: OPENGROK_SCAN_REPOS
              value: "on"
            - name: OPENGROK_SCAN_DEPTH
              value: "20"
            - name: OPENGROK_GENERATE_HISTORY
              value: "on"
            - name: OPENGROK_SUGGESTTER_ENABLED
              value: "false"
            - name: P4CONFIG
              value: ".p4config"
            - name: P4USER
              value: "svc.opengrok"
            - name: P4TICKETS
              value: "/opengrok/data/secrets/p4tickets/svc.opengrok/.p4tickets"
            - name: P4TRUST
              value: "/opengrok/data/secrets/p4trust/.p4trust"
            - name: READONLY_CONFIG_FILE
              value: "/opengrok/etc/read-only.xml"
```
