### ISSUE TITLE
History based reindex is on, however history is off. History has to be enabled for history based reindex

### ISSUE THREAD

**Issue by brenwhyte** [oracle/opengrok#4563]
**Describe the bug**
I see this error in the logs:

`2024-03-20 18:42:44,014     INFO opengrok_tools | INFO: History based reindex is on, however history is off. History has to be enabled for history based reindex.`

And I'm at a loss on how to enable history

Opengrok docker image running on k8s 

**To Reproduce**

Config from Configmap
```
apiVersion: v1
data:
  JAVA_HOME: "/opt/java/openjdk"
  JAVA_OPTS: "-Xmx8g"
  SYNC_PERIOD_MINUTES: "720" #12hrs
  OPENGROK_LOG_LEVEL: "DEBUG"
  NOMIRROR: "1"
  INDEXER_OPT: "-m 2048 -H -P -S -G --depth 10 --progress -W /opengrok/etc/configuration.xml -U http://localhost:8080/"
  OPENGROK_GENERATE_HISTORY: "ON"
  OPENGROK_RENAMED_FILES_HISTORY: "ON"
  REST_PORT: "5000"
  CHECK_INDEX: "true"
  OPENGROK_SRC_ROOT: "/opengrok/src/"
  SRC_ROOT: "/opengrok/src/"
  JDK_JAVA_OPTIONS: "--add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens jdk.compiler/com.sun.tools.javac=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED"
kind: ConfigMap
metadata:
  name: opengrok-config
  namespace: opengrok

```

How do I enable History?
I figure it's per-project but I see the "History based reindex is on, however history is off" message on container startup.

Am I missing something simple? :crossed_fingers:
